### ISSUE TITLE
Add tag filter to jbx list

### ISSUE THREAD

**Issue by joecox** [ucla-pls/jbx#6]
It would be helpful to add an option to `jbx list` such that you could print out all your benchmarks with a certain tag.  Something like

```
$ ./jbx list --benchmarks --filter dacapo-harness
avrora
batik
eclipse
...
```

The rationale for this is when someone adds a repository via `jbx add` it may simply be one benchmark but might be a collection of build scripts. In the latter case, the tag given to the collection will be the repo name, but the name of each individual benchmark will be some combination of the subfolder and the repo name.

Since the resulting name is hard to guess from a user's perspective, but the tag is obvious, and the user may want to run a single benchmark of the tag, this new `jbx list` option would help.

**Comment by kalhauge** [comment]
Jbx, is not really used this way anymore.. so I'm closing the issue.
