### ISSUE TITLE
no reference to jar in project directory

### ISSUE THREAD

**Issue by cterndrup** [ucla-pls/jbx#9]
Currently, the result of flattening a repository does not necessarily create a reference to a jar in the resulting project directory. There are certain projects that have a classes/ directory that does not contain all compiled .class files for each corresponding .java src file in the src/ directory. An example project that exhibits this issue can be found at the following path on tonga:
```/nix/store/mkf1zdjg0d5j2vcxc1hws5awyissjsba-git4fea1b3ac1_JTS_Topology_Suite-pJ6```

Specifically, the ```class com/vividsolutions/jts/algorithm/CentroidLine``` does not have a .class file under classes/ despite having a corresponding src file under src/.

The nix expression for an analysis result for this particular project is included below:
```(let buildJar=utils.buildJar;environment=jbx.env;fetchgit=nixpkgs.fetchgit;flattenRepository=utils.flattenRepository;java=jbx.java;jbx=(import /home/cterndrup/.njr/jbx/expr {env={cores=24;memory="1867 MHz DDR3";memorysize=8192;name="Tonga";ppath="/home/cterndrup/.njr/jbx/proprietary/";processor="Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz";};});nixpkgs=jbx.pkgs;utils=jbx.utils; in ((jbx.analyses.reachable-methods.comp ((utils.mkBenchmarkTemplate {build=(javaversion: ((buildJar (flattenRepository {name="git4fea1b3ac1_JTS_Topology_Suite-pJ6";sha256="0nq181zp0345sw28bcydxycizib2dc2698xy545sxz8xxiliixx7";src=(fetchgit {name="git4fea1b3ac1_JTS_Topology_Suite";rev="baf4c85832b55eb5f960e700a47531c130b0cb27";sha256="102zbqrg4sa4nfpiss4fblcaqvyb4ar8nx1b18yv74v70qpvcajz";url="https://github.com/omar711/JTS-Topology-Suite";});subfolder="";})) java.java6));inputs=[{args=[];name="empty";stdin="";}];mainclass="com.vividsolutions.jtsexample.operation.polygonize.PolygonizeExample";name="git4fea1b3ac1_JTS_Topology_Suite-pJ6-com_vividsolutions_jtsexample_operation_polygonize_PolygonizeExample";}).withJava java.java6)) environment))```

**Comment by kalhauge** [comment]
So did this turn out to be something else? Ei. that they used refection?

**Comment by cterndrup** [comment]
I think so. Although it was weird how that one .java file wasn't compiled for some reason.

**Comment by cterndrup** [comment]
@kalhauge I think we can close, unless you want to add a reference to the jar in the project directory, in which case I can update the issue description.
